/*  network_switch_interfaces.h */

#ifndef NETWORK_SWITCH_INTERFACES_H
#define NETWORK_SWITCH_INTERFACES_H

#include "network_switch_common.h"

/*  Interface to cycle based simulation.

    This simply requires the implementation of general setup functions and also
    a tick function, which is called on every simulation cycle.
    
    The tick function takes a generic argument, which might be, for example,
    the traffic to be sent to the switch in that cycle (generated by an
    external traffic generator). */
struct i_cycle_sim_switch {
    void *(*create)(port_num_t port_num);
    void (*free)(void *);
    register_result (*register_host)(void *, host_desc_t, port_num_t);
    register_result (*deregister_host)(void *, port_num_t);
    void tick(void *arg);
};

typedef struct i_cycle_sim_switch i_cycle_sim_switch_t;

/*  TODO - event switch interface. */

#endif